#!/usr/bin/env python3
"""Generate STRUCTURE.txt deterministically from the Git index.

The file is a tree-style listing of every tracked path, so it can never
include build artifacts, ignored files, or secrets that Git does not
track.  Directories are derived from the tracked file paths; the listing
is sorted bytewise for a stable output.

Usage:
    tools/gen-structure.py            # write STRUCTURE.txt
    tools/gen-structure.py --check    # exit 1 if STRUCTURE.txt is stale
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "STRUCTURE.txt"
HEADER = (
    "# Generated by tools/gen-structure.py from `git ls-files`.\n"
    "# Do not edit by hand; run `make check-structure` to validate,\n"
    "# and regenerate with `python3 tools/gen-structure.py`.\n"
)
# Tracked placeholder files that only pin empty directories.
EXCLUDED_BASENAMES = {".gitkeep"}


def tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z"],
        capture_output=True, check=True,
    )
    names = [
        name.decode("utf-8")
        for name in result.stdout.split(b"\0")
        if name
    ]
    return sorted(
        name for name in names
        if Path(name).name not in EXCLUDED_BASENAMES
    )


def render(paths: list[str]) -> str:
    lines: list[str] = [HEADER]
    emitted_dirs: set[str] = set()
    for path in paths:
        parts = path.split("/")
        for depth in range(len(parts) - 1):
            directory = "/".join(parts[: depth + 1])
            if directory not in emitted_dirs:
                emitted_dirs.add(directory)
                lines.append("  " * depth + parts[depth] + "/")
        lines.append("  " * (len(parts) - 1) + parts[-1])
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    check_only = argv == ["--check"]
    if argv and not check_only:
        print("usage: gen-structure.py [--check]", file=sys.stderr)
        return 2
    rendered = render(tracked_files())
    if check_only:
        current = OUTPUT.read_text() if OUTPUT.is_file() else ""
        if current != rendered:
            print(
                "STRUCTURE.txt is stale; regenerate with "
                "`python3 tools/gen-structure.py`",
                file=sys.stderr,
            )
            return 1
        print("structure_index=PASS")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rendered.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
